version: '2.0'
services:

  moodle:
    build: php7.0
    restart: always
    container_name: moodle
    volumes:
      - ./moodledata:/var/www/moodledata
      - ./moodle:/var/www/html/moodle
    expose: 
      - 80
    ports:
      - 81:80
    tty: true

